# includes default values: https://docs.helix-editor.com/editor.html#editor-section

theme = "haubur"

[editor]
line-number = "relative"
continue-comments = false
auto-completion = false
trim-final-newlines = true
trim-trailing-whitespace = true
auto-pairs = false
popup-border = "all"
rulers = [120]

[editor.statusline]
left = ["mode", "file-name", "position"]
center = ["version-control"]
right = ["spinner", "total-line-numbers", "diagnostics"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "bar"

[editor.file-picker]
hidden = false
