[[language]]
name = "rust"
file-types = ["rs"]
auto-format = true
roots = ["Cargo.toml", "Cargo.lock"]
diagnostic-severity = "warning"
comment-tokens = ["//", "///"]
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = "    " }
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt", args = ["--edition", "2024"] }

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[[language]]
name = "html"
auto-format = false # unfortunately, formatter breaks syntax in <code> blocks
language-servers = ["vscode-html-language-server"]

# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#pyright--ruff
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
